class Commands:
    LEECH = "gleech"
    PURGE = "purge"
    PAUSEALL = "pauseall"
    RESUMEALL = "resumeall"
    STATUS = "status"
    SETTINGS = "settings"
    EXEC = "exec"
    UPLOAD = "upload"
    YTDL = "gytdl"
    PYTDL = "gpytdl"
    ABOUT = "about"
    GETLOGS = "getlogs"
    SERVER = "server"
    USERSETTINGS = "usetting"
    INSTADL = "instadl"
